### ISSUE TITLE
Cannot run bert-efa-example example

### ISSUE THREAD

**Issue by iankouls-aws** [aws-samples/aws-efa-eks#2]
The example bert-efa-example.yaml refers to a private image 231748552833.dkr.ecr.us-east-1.amazonaws.com/bert-efa-hvd-tf1-py3:latest and gets ImagePullBackoff due to lack of permissions.

Here is the line number for reference:
https://github.com/aws-samples/aws-efa-eks/blob/main/examples/bert-efa-example.yaml#L20

If possible, please provide a public version of this image so the example is reproducible.
Thank you!

**Comment by anyingl** [comment]
Hello! I'm also having this issue with almost all of the Pytorch examples: https://github.com/aws-samples/aws-efa-eks/issues/2. It'd be great if these could be pushed to a public repo.
