### ISSUE TITLE
Public ECR repo not found for NCCL tests

### ISSUE THREAD

**Issue by ytsssun** [aws-samples/aws-efa-eks#25]
### Issue
I am trying to run the EFA EKS NCCL tests, but the public ECR image (public.ecr.aws/w6p6i9i7/aws-efa-nccl-rdma) referenced [here](https://github.com/aws-samples/aws-efa-eks/blob/main/examples/simple/nccl-efa-tests.yaml#L16C20-L16C74) no longer exists. What is the alternative for that?

Pod log:
```
Events:
  Type     Reason   Age                  From     Message
  ----     ------   ----                 ----     -------
  Normal   Pulling  59m (x4 over 61m)    kubelet  Pulling image "public.ecr.aws/w6p6i9i7/aws-efa-nccl-rdma:22.03-pt-py3"
  Warning  Failed   59m (x4 over 61m)    kubelet  Failed to pull image "public.ecr.aws/w6p6i9i7/aws-efa-nccl-rdma:22.03-pt-py3": rpc error: code = NotFound desc = failed to pull and unpack image "public.ecr.aws/w6p6i9i7/aws-efa-nccl-rdma:22.03-pt-py3": failed to resolve reference "public.ecr.aws/w6p6i9i7/aws-efa-nccl-rdma:22.03-pt-py3": public.ecr.aws/w6p6i9i7/aws-efa-nccl-rdma:22.03-pt-py3: not found
  Warning  Failed   59m (x4 over 61m)    kubelet  Error: ErrImagePull
  Warning  Failed   59m (x6 over 61m)    kubelet  Error: ImagePullBackOff
  Normal   BackOff  76s (x260 over 61m)  kubelet  Back-off pulling image "public.ecr.aws/w6p6i9i7/aws-efa-nccl-rdma:22.03-pt-py3"
```

### What I expect
I would expect to be able to run the EKA EKS NCCL tests with no problem.

**Comment by uruddarraju** [comment]
+1, running into the same issue

**Comment by bryantbiggs** [comment]
there is a new image available at `public.ecr.aws/hpc-cloud/nccl-tests:latest` which its Dockerfile can be found here https://github.com/aws-samples/awsome-distributed-training/blob/main/micro-benchmarks/nccl-tests/nccl-tests.Dockerfile
