### ISSUE TITLE
Make the aws-efa-k8s-device-plugin image publicly available 

### ISSUE THREAD

**Issue by rexminnis** [aws-samples/aws-efa-eks#26]
Hi,

Can you please make the image aws-efa-k8s-device-plugin publicly available? It's currently behind auth on ECR (602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efa-k8s-device-plugin:v0.5.3).

Thank you

**Comment by rexminnis** [comment]
Also the following package needs to be updated:

pkg:golang/stdlib@1.22.0 **upgrade to 1.22.5**
pkg:rpm/amazonlinux/glibc@2.34-52.amzn2023.0.7 **upgrade to 2.34-52.amzn2023.0.10**
pkg:rpm/amazonlinux/glibc-minimal-langpack@2.34-52.amzn2023.0.7 **upgrade to 2.34-52.amzn2023.0.10**
pkg:rpm/amazonlinux/glibc-common@2.34-52.amzn2023.0.7 **upgrade to 2.34-52.amzn2023.0.10**

**Comment by rexminnis** [comment]
Is the app product code in the container open source, MIT? If so can that be made public?

**Comment by bryantbiggs** [comment]
the Helm chart is located here https://github.com/aws/eks-charts/tree/master/stable/aws-efa-k8s-device-plugin

there are no plans at this time to make the device plugin code open source - there isn't anything proprietary, it just adds more overhead in terms of maintaining in a public forum.
