### ISSUE TITLE
Add c5n.9xlarge to instance list

### ISSUE THREAD

**Issue by daniel-pebble** [aws-samples/aws-efa-eks#6]
Can you please add c5n.9xlarge to the instance list in https://github.com/aws-samples/aws-efa-eks/blob/main/manifest/efa-k8s-device-plugin.yml

**Comment by amrragab8080** [comment]
Done
https://github.com/aws-samples/aws-efa-eks/commit/a40a5b96d983d194861dc37bd2041542d42c340e
